---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sentry
  namespace: sentry
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:sentry-kubernetes/charts.git
    path: sentry
    ref: 5.2.2
  values:
    postgresql:
      postgresqlPassword: somepassword
    ingress:
      enabled: true
    nginx:
      enabled: false
