---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: sealed-secrets-controller
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    path: sealed-secrets
    version: 1.10.3

